/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0 and the Server Side Public License, v 1; you may not use this file except
 * in compliance with, at your election, the Elastic License 2.0 or the Server
 * Side Public License, v 1.
 */

buildscript {
    def gradleProps = new Properties()
    new File(projectDir, 'gradle.properties').withInputStream { gradleProps.load(it) }
    ext.es_version = gradleProps.getProperty('elasticsearchVersion')
    repositories {
        maven {
            url = 'https://snapshots.elastic.co/maven/'
        }
        mavenCentral()
    }
    dependencies {
        classpath "org.elasticsearch.gradle:build-tools:${es_version}"
    }
}

apply plugin: 'java'
apply plugin: 'elasticsearch.esplugin'
apply plugin: 'elasticsearch.yaml-rest-test'

tasks.withType(JavaCompile) {
    options.compilerArgs << "-Xlint:unchecked,deprecation"
}

test {
    enabled = true
    useJUnit()
}

esplugin {
    name = pluginName
    description = pluginDescription
    classname = pluginClassname
    licenseFile = rootProject.file("LICENSE.txt")
    noticeFile = rootProject.file("NOTICE.txt")
}

allprojects {
    repositories {
      mavenCentral()
    }
}

dependencies {
    implementation 'org.roaringbitmap:RoaringBitmap:0.9.35'

    testImplementation 'junit:junit:4.13.2'

    yamlRestTestImplementation "org.apache.logging.log4j:log4j-core:2.19.0"
    yamlRestTestImplementation "org.elasticsearch.test:framework:$es_version"
    yamlRestTestImplementation "org.elasticsearch.test:yaml-rest-runner:$es_version"
}
